version: "2"
run:
  go: '1.25'
  tests: false
output:
  show-stats: false
issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  fix: true
linters:
  default: none
  exclusions:
    generated: strict
    paths:
      - frontend$
      - configs$
      - internal/testutils$
      - '\\.md$'
    presets:
      - legacy
  settings:
    errcheck:
      check-type-assertions: false
      custom-order: true
    gocritic:
      disabled-checks:
        - unnamedResult
        - whyNoLint
        - hugeParam
        - elseif
        - singleCaseSwitch
      enabled-tags:
        - diagnostic
        - style
        - performance
    govet:
      enable-all: true
      disable:
        - shadow
        - tests
    misspell:
      locale: US
      ignore-rules:
        - cancelled
        - cancelling
    prealloc:
      for-loops: true
    revive:
      severity: error
      enable-all-rules: true
      confidence: 0.1
      rules:
        - name: add-constant
          disabled: true
        - name: argument-limit
          disabled: true
        - name: banned-characters
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: deep-exit
          disabled: true
        - name: file-header
          disabled: true
        - name: function-length
          disabled: true
        - name: function-length
          disabled: true
        - name: function-result-limit
          arguments: [ 99 ]
        - name: import-shadowing
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: modifies-parameter
          disabled: true
        - name: nested-structs
          disabled: true
        - name: unhandled-error
          severity: warning
        - name: var-naming
          severity: warning
        - name: if-return
          severity: error
        - name: flag-parameter
          disabled: true
    staticcheck:
      checks: [ "all", "-SA1019" ]
formatters:
  enable:
    - gci
    - gofumpt
    - goimports



