name: Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_ID: aviseu-jobs
  WORKLOAD_IDENTITY_PROVIDER: projects/911924781524/locations/global/workloadIdentityPools/github-actions/providers/github
  SERVICE_ACCOUNT: github@aviseu-jobs.iam.gserviceaccount.com
  REGION: europe-west4
  TRIGGER_REGION: europe-west3
  GCLOUD_REPOSITORY: jobs

jobs:
  build-and-push-backend:
    name: Build and Push (backend)
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    strategy:
      matrix:
        app: [import, api, schedule]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Configure docker auth
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          buildkitd-flags: --debug
          driver-opts: |
            image=moby/buildkit:master

      - name: Docker subscriber meta (${{ matrix.app }})
        id: subscriber_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GCLOUD_REPOSITORY }}/${{ github.event.repository.name }}-${{ matrix.app }}
          flavor: |
            latest=auto
          tags: |
            type=sha,format=long,priority=40

      - name: Build and push (${{ matrix.app }})
        uses: docker/build-push-action@v6
        with:
          target: job
          context: .
          push: true
          tags: ${{ steps.subscriber_meta.outputs.tags }}
          build-args: |
            APP=${{ matrix.app }}

  build-and-push-frontend:
    name: Build and Push (frontend)
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Configure docker auth
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          buildkitd-flags: --debug
          driver-opts: |
            image=moby/buildkit:master

      - name: Docker subscriber meta (backoffice-frontend)
        id: subscriber_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GCLOUD_REPOSITORY }}/${{ github.event.repository.name }}-frontend
          flavor: |
            latest=auto
          tags: |
            type=sha,format=long,priority=40

      - name: Build and push (api-frontend)
        uses: docker/build-push-action@v6
        with:
          target: frontend
          context: frontend
          push: true
          tags: ${{ steps.subscriber_meta.outputs.tags }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    needs: [build-and-push-backend, build-and-push-frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |-
          cd terraform
          terraform init

      - name: Terraform Validate
        run: |-
          cd terraform
          terraform validate -no-color

      - name: Terraform Plan
        run: |-
          cd terraform
          terraform plan -no-color \
            -var project_id=${{ env.PROJECT_ID }} \
            -var region=${{ env.REGION }} \
            -var frontend_container_image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GCLOUD_REPOSITORY }}/${{ github.event.repository.name }}-frontend \
            -var api_container_image=$${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GCLOUD_REPOSITORY }}/${{ github.event.repository.name }}-api \
            -var schedule_container_image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GCLOUD_REPOSITORY }}/${{ github.event.repository.name }}-schedule \
            -var import_container_image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GCLOUD_REPOSITORY }}/${{ github.event.repository.name }}-import \
            -var image_tag=sha-${{ github.sha }} \
            -var trigger_region=${{ env.TRIGGER_REGION }}

      - name: Terraform Apply
        run: |-
          cd terraform
          terraform apply -auto-approve -no-color -parallelism 5 \
            -var project_id=${{ env.PROJECT_ID }} \
            -var region=${{ env.REGION }} \
            -var frontend_container_image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GCLOUD_REPOSITORY }}/${{ github.event.repository.name }}-frontend \
            -var api_container_image=$${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GCLOUD_REPOSITORY }}/${{ github.event.repository.name }}-api \
            -var schedule_container_image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GCLOUD_REPOSITORY }}/${{ github.event.repository.name }}-schedule \
            -var import_container_image=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GCLOUD_REPOSITORY }}/${{ github.event.repository.name }}-import \
            -var image_tag=sha-${{ github.sha }} \
            -var trigger_region=${{ env.TRIGGER_REGION }}
