name: Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PROJECT_ID: aviseu-jobs
  WORKLOAD_IDENTITY_PROVIDER: projects/911924781524/locations/global/workloadIdentityPools/github-actions/providers/github
  SERVICE_ACCOUNT: github@aviseu-jobs.iam.gserviceaccount.com
  REGION: us-central1
  ZONE: us-central1-c
  GCLOUD_REPOSITORY: jobs

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        name: Authenticate
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Configure docker auth
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          buildkitd-flags: --debug
          driver-opts: |
            image=moby/buildkit:master

      - name: Docker subscriber meta (import)
        id: subscriber_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GCLOUD_REPOSITORY }}/${{ github.event.repository.name }}-import
          flavor: |
            latest=auto
          tags: |
            type=sha,format=long,priority=40

      - name: Build and push (import)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.subscriber_meta.outputs.tags }}
          build-args: |
            APP=${{ matrix.app }}
