name: Add Dependabot PRs to Project

on:
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
#    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Add PR to Project
        uses: actions/github-script@v6
        with:
          script: |
            const projectNumber = 1;
            const columnName = "Pending";
            gh api graphql -f query='
              mutation($projectNumber: Int! $contentId: Int!) {
                addProjectV2ItemById(input: {projectId: $projectNumber contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }' -f projectNumber=$projectNumber -F contentId=context.payload.pull_request.id
