name: Add Dependabot PRs to Project

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  add-to-project:
#    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Add PR to Project
        uses: actions/github-script@v7
        with:
          script: |
            const query = `mutation($projectNumber: Int! $contentId: Int!) {
                addProjectV2ItemById(input: {projectId: $projectNumber contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }`
            const variables = {
              projectNumber: 1,
              contentId: context.payload.pull_request.id
            };
            const result = await github.graphql(query, variables);
            console.log(result);
