name: Add Dependabot PRs to Project

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  add-to-project:
#    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Add PR to Project
        uses: actions/github-script@v7
        with:
          script: |
            const queryProjectID = `
            query($organization: String! $number: Int!) {
              organization(login: $organization) {
                projectV2(number: $number) {
                  id
                }
              }
            }`;
            const variablesProjectID = {
              number: 1,
              organization: "aviseu"
            };
            const resultProjectID = await github.graphql(queryProjectID, variablesProjectID);
            
            const query = `mutation($projectId: ID! $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }`
            const variables = {
              projectId: result.organization.projectV2.id,
              contentId: context.payload.pull_request.id
            };
            const result = await github.graphql(query, variables);
            console.log(result);
